name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Repository ID
        run: echo "Repository ID = ${{ github.repository_id }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./environment_dev
        run: terraform init

      - name: Terraform Validate
        working-directory: ./environment_dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./environment_dev
        run: terraform plan -var-file=terraform.ci.tfvars -input=false